server:
  port: ${PORT:3000}

spring:
  profiles: default
  redis:
    host: ${REDIS_SERVER:localhost}
    port: 6379
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: route_payment
          uri: ${ROOT_PAYMENT:http://localhost:3001/}
          predicates:
            - Path=/payments/**,/docs/payments
          filters:
            - name: CircuitBreaker
              args:
                - name: paymentCircuitBreaker
                  fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: route_account
          uri: ${ROOT_ACCOUNT:http://localhost:3002/}
          predicates:
            - Path=/accounts/**,/docs/accounts
          filters:
            - name: CircuitBreaker
              args:
                - name: accountCircuitBreaker
                  fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

logging:
  level:
    io.github.resilience4j: DEBUG
    org.acme.financial.api: DEBUG
    org.springframework.cloud.gateway: DEBUG

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /docs
    urls:
      - name: payments
        url: /docs/payments
      - name: accounts
        url: /docs/accounts
