server:
  port: ${PORT:3000}

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: route_payment
          uri: ${ROUTE_PAYMENT:http://localhost:3001/}
          predicates:
            - Path=/payments/**
        - id: route_account
          uri: ${ROUTE_ACCOUNT:http://localhost:3002/}
          predicates:
            - Path=/accounts/**

logging:
  level:
    org.acme.financial.api: DEBUG

