server:
  port: ${PORT:3000}

spring:
  profiles: default
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: route_payment
          uri: ${ROOT_PAYMENT:http://localhost:3001/}
          predicates:
            - Path=/payments/**,/docs/payments
        - id: route_account
          uri: ${ROOT_ACCOUNT:http://localhost:3002/}
          predicates:
            - Path=/accounts/**,/docs/accounts

logging:
  level:
    org.acme.financial.api: DEBUG
    org.springframework.cloud.gateway: DEBUG

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /docs
    urls:
      - name: payments
        url: /docs/payments
      - name: accounts
        url: /docs/accounts
