server:
  port: ${PORT:3001}

spring:
  profiles:
    include: actuator,logging
  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: payment
    password: payment
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
  liquibase:
    change-log: classpath:db/changelog.yml
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      group-id: ${KAFKA_PAYMENT_GROUP_ID:payment_group_id}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.acme.financial.payments: DEBUG

acme:
  payment:
    security:
      user:
        account-id: 123e4567-e89b-12d3-a456-426655440000
        username: username
        password: password
        role: USER
    topics:
      payment-transaction-started: ${ACME_PAYMENT_TRX_STARTED_TOPIC:payment-transaction-started-topic}
      payment-transaction-completed: ${ACME_PAYMENT_TRX_COMPLETED_TOPIC:payment-transaction-completed-topic}