server:
  port: ${PORT:3001}

spring:
  profiles:
    include: actuator,logging
  jpa:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
  liquibase:
    change-log: classpath:db/changelog.yml
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      group-id: ${KAFKA_PAYMENT_GROUP_ID:payment_group_id}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      # Uncomment to use string deserializer instead
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      # Uncomment to use string serializer instead
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # Schema registry
    auto.register.schemas: true
    schema.registry.url: ${KAFKA_SCHEMA_SERVER:localhost:8081}
    value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy

logging:
  level:
    org.acme.commons: DEBUG
    org.acme.financial.payments: DEBUG
    #org.springframework.orm.jpa: DEBUG
    #org.springframework.transaction: DEBUG

springdoc:
  api-docs:
    path: /docs/payments

acme:
  payment:
    security:
      users:
        user-primary:
          account-id: 123e4567-e89b-12d3-a456-426655440001
          username: AT483200000000000001
          password: password
          role: USER
        user-secondary:
          account-id: 123e4567-e89b-12d3-a456-426655440002
          username: AT483200000000000002
          password: password
          role: USER
    topics:
      single-payment-started: ${ACME_SINGLE_PAYMENT_STARTED_TOPIC:single-payment-started-topic}
      single-payment-completed: ${ACME_SINGLE_PAYMENT_COMPLETED_TOPIC:single-payment-completed-topic}
      single-payment-completed-dlq: ${ACME_SINGLE_PAYMENT_COMPLETED_TOPIC_DLQ:single-payment-completed-topic-dlq}