server:
  port: ${PORT:3002}

spring:
  profiles:
    include: actuator,logging
  jpa:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
  liquibase:
    change-log: classpath:db/changelog.yml
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      group-id: ${KAFKA_PAYMENT_GROUP_ID:account_group_id}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.acme.commons: DEBUG
    org.acme.financial.accounts: DEBUG
    #org.springframework.orm.jpa: DEBUG
    #org.springframework.transaction: DEBUG

springdoc:
  api-docs:
    path: /docs/accounts

acme:
  account:
    security:
      users:
        user-primary:
          account-id: 123e4567-e89b-12d3-a456-426655440001
          username: AT483200000000000001
          password: password
          role: USER
        user-secondary:
          account-id: 123e4567-e89b-12d3-a456-426655440002
          username: AT483200000000000002
          password: password
          role: USER
    topics:
      single-payment-started: ${ACME_SINGLE_PAYMENT_STARTED_TOPIC:single-payment-started-topic}
      single-payment-started-dlq: ${ACME_SINGLE_PAYMENT_STARTED_TOPIC_DLQ:single-payment-started-topic-dlq}
      single-payment-completed: ${ACME_SINGLE_PAYMENT_COMPLETED_TOPIC:single-payment-completed-topic}